<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Online Privacy Policy Form Generator - GoTech</title>
<link href="css/bootstrap.min.css" rel="stylesheet">
<link href="css/main.css" rel="stylesheet">
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->

<style type="text/css">
.blocks {
	padding: 20px 20px;
	background: #66A3C2;
	width: 95%;
	height: 150px;
	border-radius: 30px;
	font-family: "Trebuchet MS", Helvetica, sans-serif;
	font-size: 90%;
	color: #00478F;
	text-align: center;
}

.blocks:hover {
	padding: 20px 20px;
	background: #00476B;
	width: 95%;
	height: 150px;
	border-radius: 30px;
	font-family: "Trebuchet MS", Helvetica, sans-serif;
	font-size: 90%;
	color: #99ADD6;
	text-align: center;
}

#blockref {
	color: #FFFFFF;
	font-size: 200%;
	text-decoration: none;
}

.buttontable {
	width: 80%;
	margin-top: 100px;
	margin-bottom: 100px;
}
</style>
</head>
<script
	src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="js/bootstrap.min.js"></script>
<body>
	<div class="container">
		<div style="margin: 50px">
			<h1 style="color: #00476B; text-align: center">Online Privacy
				Form Generator</h1>
			<hr/>
			<p style="color: #66A3C2; font-size: 120%; text-align: center; letter-spacing:4px">CONSISTENT, CORRECT AND FREE
				ONLINE POLICY FORM GENERATOR.</p>
		</div>

		<div align="center">
			<table class="buttontable">
				<tr style="text-align: center">
					<td style="width: 50%" align="center">
						<div class="blocks">
							<a href="page0.do" id="blockref">Create New Privacy
								Form</a> <br />
							<p style="font-size: 140%">I want to create a new privacy
								form.</p>
						</div>
					</td>
					<td style="width: 50%" align="center">
						<div class="blocks">
							<a href="upload.do" id="blockref">Resume From Backup File</a>
							<br />
							<p style="font-size: 140%">I want to resume from a backup
								file generated by the website.</p>
						</div>
					</td>
				</tr>
			</table>
		</div>
	</div>
	
	<div style="margin: 50px">
		<p style="color: #00476B; text-align: center">
			Team GoTech @ 2014
		</p>
	</div>
</body>
</html>